version: 0.1

phases:
  pre_build:
    commands:
      - npm install
      - echo "Arguments received:"
      - echo "ENV_TYPE=$ENV_TYPE"
      - echo "SNS_TOPIC_ARN=$SNS_TOPIC_ARN"
      - echo "REGION=$REGION"
      - echo "AWS_REGION=$AWS_REGION"
  build:
    commands:
      - echo Build started on `date`
      - sls deploy | tee deploy.log
  post_build:
    commands: 
      - echo Build completed on `date`
      - export SUBJECT="Hezuo Code Build Complete ENV=$ENV_TYPE"
      - export MESSAGE=$(<deploy.log)
      - python ~/hezuo-builder/publish.py
