version: 0.1

environment_variables:
  plaintext:
    MY_ENV: $ENV_TYPE 

phases:
  pre_build:
    commands:
      - npm install
      - echo "Arguments received:"
      - echo "ENV_TYPE=$ENV_TYPE"
      - echo "SNS_TOPIC_ARN=$SNS_TOPIC_ARN"
  build:
    commands:
      - echo Build started on `date`
      - sls deploy | tee deploy.log
  post_build:
    commands: 
      - echo Build completed on `date`
      - export MESSAGE=$(cat deploy.log | sed "s/\"/\'/g")
      - export MY_ENV=$ENV_TYPE
      - export SUBJECT="AWS CodeBuild - Hezuo - ENV=$ENV_TYPE - Build Completed"
      - aws sns publish --topic-arn $SNS_TOPIC_ARN --subject $SUBJECT --message $MESSAGE
