version: 0.1

environment_variables:
  plaintext:
    MY_ENV: $ENV_TYPE 

phases:
  pre_build:
    commands:
      - npm install
      - echo "Arguments received:"
      - echo "ENV_TYPE=$ENV_TYPE"
      - echo "SNS_TOPIC_ARN=$SNS_TOPIC_ARN"
  build:
    commands:
      - echo Build started on `date`
      - sls deploy | tee deploy.log
  post_build:
    commands: 
      - echo Build completed on `date`
      - MESSAGE=$(cat deploy.log | sed "s/\"/\'/g")
      - aws sns publish --topic-arn "$SNS_TOPIC_ARN" --subject 'AWS CodeBuild - Hezuo - ENV="$ENV_TYPE",MY_ENV="$MY_ENV" - Build Completed' --message '"$MESSAGE"' 
